name: Install and Start NGINX

on: 
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  setup-nginx:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update and install NGINX
        run: |
          sudo apt-get update
          sudo apt-get install -y nginx

      - name: Start NGINX service
        run: |
          sudo systemctl start nginx
          sudo systemctl status nginx

      - name: Verify NGINX is running
        run: curl -I http://localhost
